include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - omit_local_variable_types
    - require_trailing_commas
    - prefer_final_locals

analyzer:
  exclude:
    - lib/generated/**
    - test/generated/**
    - '**/*.g.dart'
    - '**/*.freezed.dart'
