name: gha_visual_editor
description: "GitHub Actions' Visual Editor"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.5.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  signals: ^5.4.0
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
